# Generated by Django 4.1.7 on 2023-03-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='caution',
            field=models.TextField(null=True, verbose_name='주의사항'),
        ),
    ]
